# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "demo-tlspass.fullname" . }}
  namespace: istio-system
  annotations:
    externaldns: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    {{- include "demo-tlspass.labels" . | nindent 4 }}
spec:
  ingressClassName: platform
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          service:
            name: istio-ingressgateway-public
            port:
              number: 443
        path: /
        pathType: Prefix
