# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "demo-tlspass.fullname" . }}
  labels:
    {{- include "demo-tlspass.labels" . | nindent 4 }}
spec:
  gateways:
  - {{ .Release.Namespace }}/{{ include "demo-tlspass.fullname" . }}
  hosts:
  - {{ .Values.host }}
  tls:
  - match:
    - port: 443
      sniHosts:
      -  {{ .Values.host }}
    route:
    - destination:
        host: {{ include "demo-tlspass.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 443
