bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: istio-operator
    installed: true
    namespace: istio-operator
    disableValidationOnInstall: true
    labels:
      pkg: istio
    <<: *default
  - name: kiali-operator
    installed: {{ $a | get "kiali.enabled" }}
    namespace: kiali-operator
    needs: kiali/kiali-operator-artifacts
    disableValidationOnInstall: true
    labels:
      pkg: kiali
    <<: *default
  - name: kiali-operator-artifacts
    installed: {{ $a | get "kiali.enabled" }}
    namespace: kiali
    labels:
      pkg: kiali
    <<: *raw
  - name: vault-operator
    installed: {{ $a | get "vault.enabled" }}
    disableValidationOnInstall: true
    namespace: vault
    labels:
      pkg: vault
    <<: *default
