bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: otomi-api
    installed: true
    namespace: otomi
    <<: *default
  - name: otomi-console
    installed: true
    namespace: otomi
    <<: *default