bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: argocd-operator
    installed: {{ $a | get "argocd.enabled" }}
    namespace: argocd
    labels:
      pkg: argocd
    <<: *default
  - name: gitea-artifacts
    installed: {{ $a | get "gitea.enabled" }}
    namespace: gitea
    labels:
      pkg: gitea
    <<: *raw
  - name: kiali-operator-artifacts
    installed: {{ $a | get "kiali.enabled" }}
    namespace: kiali
    labels:
      pkg: kiali
    <<: *raw
  - name: knative-serving-artifacts
    installed: {{ $a | get "knative.enabled" }}
    namespace: knative-serving
    needs: [default/knative-operator]
    chart: ../charts/raw
    labels:
      init: true
      pkg: knative
    values:
      - ../values/knative/knative-serving-raw.gotmpl
    <<: *upgrade
  - name: knative-operator
    installed: {{ $a | get "knative.enabled" }}
    namespace: default
    labels:
      init: true
      pkg: knative
    <<: *skeleton
  - name: loki-artifacts
    installed: {{ $a | get "loki.enabled" }}
    namespace: monitoring
    labels:
      pkg: loki
    <<: *raw
  - name: vault-operator
    installed: {{ $a | get "vault.enabled" }}
    disableValidationOnInstall: true
    namespace: vault
    chart: ../charts/vault-operator
    labels:
      pkg: vault
    values:
      - ../values/vault-operator/vault-operator.gotmpl
      - {{- $v.apps.vault | get "_rawValues" dict | toYaml | nindent 8 }}
    <<: *upgrade
