bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}
{{- $tca := $v.teamConfig.admin }}
{{- $s := tpl (readFile "../helmfile.d/snippets/services.gotmpl") $v | fromYaml }}

releases:
  - name: core-ingress
    installed: true
    namespace: otomi-core
    chart: ../charts/team-ns
    labels:
      ingress: 'true'
    values:
      - name: core
        teamId: core
        apps: {{- $a | toYaml | nindent 10 }}
        oidc: {{- $v.oidc | toYaml | nindent 10 }}
        cluster: {{- $v.cluster | toYaml | nindent 10 }}
        otomi: {{- $v.otomi | toYaml | nindent 10 }}
        domain: {{ $v.cluster.domainSuffix }}
        services: {{- $s.coreAdminServices | toYaml | nindent 10 }}
        resourceQuota: null
        ingress: {{- $v.ingress | toYaml | nindent 10 }}
