bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: host-mods
    installed: {{ $a | get "host-mods.enabled" }}
    namespace: kube-system
    labels:
      pkg: host
    <<: *default
