bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

# Gatekeeper is the first to be installed because it runs a mutating webhook assigning node affinity

releases:
  - name: gatekeeper
    installed: {{ $a | get "gatekeeper.enabled" }}
    namespace: gatekeeper-system
    chart: ../charts/gatekeeper
    disableValidationOnInstall: true
    labels:
      pkg: gatekeeper
    values:
      - ../values/gatekeeper/gatekeeper.gotmpl
      - snippets/common.gotmpl
    <<: *upgrade
  - name: gatekeeper-artifacts
    installed: {{ $a | get "gatekeeper.enabled" }}
    namespace: gatekeeper-system
    chart: ../charts/gatekeeper-artifacts
    needs: [gatekeeper]
    labels:
      pkg: gatekeeper
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "../bin/build-gatekeeper-artifacts.sh"
        args: [true]
    values:
      - ../values/gatekeeper/gatekeeper-artifacts.gotmpl
      - snippets/common.gotmpl
  - name: gatekeeper-constraints
    installed: {{ $a | get "gatekeeper.enabled" }}
    namespace: gatekeeper-system
    needs: [gatekeeper-artifacts]
    chart: ../charts/gatekeeper-constraints
    labels:
      pkg: gatekeeper
    values:
      - snippets/common.gotmpl
