bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: demo-tlspass
    installed: {{ $a | get "demo-tlspass.enabled" }}
    namespace: team-otomi
    <<: *default
  - name: harbor
    installed: {{ $a | get "harbor.enabled" }}
    namespace: harbor
    labels:
      pkg: harbor
    <<: *default
  - name: hello
    installed: {{ $a | get "hello.enabled" }}
    namespace: team-otomi
    <<: *default
  - name: httpbin
    installed: {{ $a | get "httpbin.enabled" }}
    namespace: httpbin
    <<: *default
  - name: kubeapps
    installed: {{ $a | get "kubeapps.enabled" }}
    namespace: kubeapps
    labels:
      pkg: kubeapps
    <<: *default
  - name: kubeclarity
    installed: {{ $a | get "kubeclarity.enabled" }}
    namespace: kubeclarity
    labels:
      pkg: kubeclarity
    <<: *default
  - name: redis-shared
    installed: {{ $a | get "redis-shared.enabled" }}
    namespace: redis
    <<: *default
    chart: ../charts/redis
