bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: operator-lifecycle-manager
    installed: true
    namespace: operator-lifecycle-manager
    labels:
      olm: true
    <<: *default
