bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: grafana-dashboards
    installed: {{ $a | get "grafana.enabled" }}
    namespace: grafana
    <<: *default
  - name: jaeger-operator
    installed: {{ $a | get "jaeger.enabled" }}
    namespace: jaeger-operator
    disableValidationOnInstall: true
    chart: ../charts/jaeger-operator
    values:
      - ../values/jaeger-operator/jaeger-operator.gotmpl
      - {{- $v.apps.jaeger | get "_rawValues" dict | toYaml | nindent 8 }}
    <<: *upgrade
  - name: kiali-operator
    installed: {{ $a | get "kiali.enabled" }}
    namespace: kiali-operator
    disableValidationOnInstall: true
    labels:
      pkg: kiali
    chart: ../charts/kiali-operator
    values:
      - ../values/kiali-operator/kiali-operator.gotmpl
      - {{- $v.apps.kiali | get "_rawValues" dict | toYaml | nindent 8 }}
    <<: *upgrade
  - name: loki
    installed: {{ $a | get "loki.enabled" }}
    namespace: monitoring
    <<: *default
  - name: prometheus-blackbox-exporter
    installed: {{ $a | get "prometheus.enabled" }} 
    namespace: monitoring
    <<: *default
  - name: promtail
    installed: {{ $a | get "loki.enabled" }}
    namespace: monitoring
    <<: *default
  - name: prometheus-msteams
    installed: {{ $a | get "prometheus-msteams.enabled" }}
    namespace: monitoring
    <<: *default
