bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: cert-manager
    installed: true
    namespace: cert-manager
    labels:
      pkg: cert-manager
    <<: *default
  - name: cert-manager-artifacts
    installed: true
    namespace: cert-manager
    needs: [cert-manager]
    labels:
      pkg: cert-manager
    <<: *raw
