bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: knative-operator
    installed: {{ $a | get "knative.enabled" }}
    namespace: knative-operator
    labels:
      init: true
      pkg: knative
    <<: *skeleton
  - name: knative-serving
    installed: {{ $a | get "knative.enabled" }}
    namespace: knative-serving
    chart: ../charts/raw-cr
    disableValidationOnInstall: true
    needs:
      - knative-serving/knative-serving-artifacts
      - knative-operator/knative-operator
    labels:
      pkg: knative
    values:
      - ../values/knative/knative-serving-cr.gotmpl
      - snippets/common.gotmpl
    <<: *upgrade
  - name: knative-serving-artifacts
    installed: {{ $a | get "knative.enabled" }}
    namespace: knative-serving
    chart: ../charts/raw
    labels:
      init: true
      pkg: knative
    values:
      - ../values/knative/knative-serving-raw.gotmpl
    <<: *upgrade
