bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: job-certs-aws
    installed:  {{ $a | get "aws-alb-ingress-controller.enabled" }}
    <<: *jobs
    labels:
      job: true
      type: cronjob
  - name: job-copy-certs
    installed:  {{ not ($a | get "aws-alb-ingress-controller.enabled") }}
    <<: *jobs
    labels:
      job: true
      type: cronjob
