bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: keycloak
    installed: true
    namespace: keycloak
    labels:
      pkg: keycloak
    <<: *default
  - name: job-keycloak
    installed: true
    needs: [keycloak]
    labels:
      pkg: keycloak
      job: true
    <<: *jobs
  - name: wait-for-otomi-realm
    installed: true
    needs: [job-keycloak]
    <<: *wait
    namespace: maintenance
    labels:
      pkg: wait
    values:
      # - url: {{ $v._derived.oidcBaseUrlBackchannel }}
      - url: {{ $v._derived.oidcBaseUrl }}
        host: keycloak.{{ $v.cluster | get "domainSuffix" nil }}
        tasksVersion: {{ $v.versions.tasks }}
        {{- if $v._derived.untrustedCA }}
        customCa: |
          {{- $v._derived.caCert | nindent 10 }}
        {{- end }}
        runPolicy: OnSpecChange

