bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: jaeger-operator
    installed: {{ $a | get "jaeger.enabled" }}
    namespace: jaeger-operator
    disableValidationOnInstall: true
    chart: ../charts/jaeger-operator
    values:
      - ../values/jaeger-operator/jaeger-operator.gotmpl
      - {{- $v.apps.jaeger | get "_rawValues" dict | toYaml | nindent 8 }}
    <<: *upgrade
