bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
{{- range $index, $ingress := $v.ingress.classes }}
  - name: ingress-nginx-{{ $ingress.className }}
    installed: true
    namespace: ingress
    labels:
      tag: ingress
      stage: prep
      class: {{ $ingress.className }}
      index: {{ $index }}
    missingFileHandler: Debug
    chart: ../charts/ingress-nginx
    values:
      - ../values/ingress-nginx/ingress-nginx.gotmpl
  {{ if eq $ingress.className "platform" }}
    <<: *upgrade
  {{- end }}
{{- end }}
