bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: drone
    installed: {{ $a | get "drone.enabled" }}
    namespace: team-admin
    labels:
      pkg: drone
    <<: *default
  - name: drone-admit-members
    installed: {{ $a | get "drone-admit-members.enabled" }}
    namespace: team-admin
    labels:
      pkg: drone
    chart: ../charts/drone-admit-members
    values:
      - ../values/drone/drone-admit-members.gotmpl
      - snippets/common.gotmpl
